apiVersion: v1                       # Los Services están en la API "core", por eso es solo v1.
kind: Service                        # Tipo de recurso: un Service (punto de acceso estable a pods).
metadata:
  name: cicd-demo-app                # Nombre del Service. Además es su nombre DNS dentro del
  # cluster: otros pods pueden llamarlo en http://cicd-demo-app:8080
spec:
  type: NodePort                     # Cómo se expone:
    #   ClusterIP (default): solo accesible dentro del cluster
    #   NodePort: además abre un puerto en cada nodo
  #   LoadBalancer: IP externa (en la nube)
  selector:
    app: cicd-demo-app               # Manda el tráfico a los pods con esta etiqueta,
    # o sea, los que creó tu Deployment.
  ports:
    - port: 8080                     # Puerto del Service (el que usan otros pods dentro del cluster).
      targetPort: 8080               # Puerto del contenedor al que reenvía.
      # Tiene que coincidir con el containerPort de la app.
      nodePort: 30080                # Puerto abierto en el nodo, accesible desde fuera.
      # Rango permitido: 30000-32767.